definitions:
  responses.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  responses.Vehicle:
    properties:
      brand:
        type: string
      color:
        type: string
      created_at:
        type: string
      entity_id:
        type: string
      id:
        type: string
      model:
        type: string
      price:
        type: number
      updated_at:
        type: string
      year:
        type: integer
    type: object
  vehicleApi.createVehicleRequest:
    properties:
      brand:
        type: string
      color:
        type: string
      model:
        type: string
      price:
        type: number
      year:
        type: integer
    required:
    - brand
    - color
    - model
    - price
    - year
    type: object
  vehicleApi.updateVehicleRequest:
    properties:
      brand:
        type: string
      color:
        type: string
      model:
        type: string
      price:
        type: number
      year:
        type: integer
    type: object
info:
  contact: {}
paths:
  /vehicles:
    post:
      consumes:
      - application/json
      description: Create vehicle
      parameters:
      - description: Body
        in: body
        name: vehicle
        required: true
        schema:
          $ref: '#/definitions/vehicleApi.createVehicleRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/responses.Vehicle'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
      summary: Create Vehicle
      tags:
      - Vehicle
  /vehicles/{entity_id}:
    patch:
      consumes:
      - application/json
      description: Update vehicle
      parameters:
      - description: Body
        in: body
        name: vehicle
        schema:
          $ref: '#/definitions/vehicleApi.updateVehicleRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.Vehicle'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
      summary: Update Vehicle
      tags:
      - Vehicle
swagger: "2.0"
