services:
  mongo:
    image: mongo:latest
    container_name: mongo-vehicle-platform-core
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: docker
      MONGO_INITDB_ROOT_PASSWORD: docker
    volumes:
      - mongo_data:/data/db
    networks:
      - shared_network

  vehicle-platform-core:
    build: .
    container_name: api-vehicle-platform-core
    restart: always
    depends_on:
      - mongo
    ports:
      - "4001:4001"
    environment:
      API_PORT: "4001"
      DB_HOST: "postgres"
      DB_PORT: "5432"
      DB_USER: "docker"
      DB_PASSWORD: "docker"
      DB_NAME: "vehicle-platform-core"
      VEHICLE_PLATFORM_SALES_HOST: "http://vehicle-platform-sales:4002"
    networks:
      - shared_network

volumes:
  mongo_data:

networks:
  shared_network:
    external: true
